version: 2
jobs:
  build-node:
    docker:
      - image: cimg/node:16.4.0

    working_directory: ~/repo

    steps:
      #- add_ssh_keys:
      #    fingerprints:
      #      - "e0:f1:7b:8c:b1:4c:49:6f:b9:bd:af:84:6d:dd:93:cb"
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: cp .circleci/mock.env.json .env.json
      - run: sudo npm install -g grunt sass
      - run: grunt build --force
      # for next steps example check lightning_sphinx_theme repo

  build-python:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: python setup.py install --dry-run --user


workflows:
  version: 2
  commit-and-build:
      jobs:
        - build-node
        - build-python
